using Prism.Mvvm;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WpfDataGridSampleApp.Models
{
    public class Main : BindableBase
    {
        public ObservableCollection<Scenario> Scenarios { get; } = new ObservableCollection<Scenario>(new[] 
        {
            new Scenario { Name = "列自動生成", ViewName = "AutoGeneratedView" },
            new Scenario { Name = "カスタム列自動生成", ViewName = "CustomAutoGeneratedColumnView" },
            new Scenario { Name = "列の定義", ViewName = "ColumnsView" },
            new Scenario { Name = "パフォーマンス", ViewName = "LargeColumnPerformanceView" },
        });

        public ReadOnlyObservableCollection<EnumLabelPair<Gender>> Genders { get; } = new ReadOnlyObservableCollection<EnumLabelPair<Gender>>(
            new ObservableCollection<EnumLabelPair<Gender>>(EnumLabelPair.CreateFromDisplayAttribute<Gender>()));

        public ObservableCollection<Person> People { get; } = new ObservableCollection<Person>(Enumerable.Range(1, 10000)
            .Select(x => new Person
            {
                Name = $"tanaka {x}",
                Age = (30 + x % 10).ToString(),
                Gender = x % 2 == 0 ? Gender.Men : Gender.Women,
            }));
    }
}
